apiVersion: v1
kind: Service
metadata:
  name: {{ template "Springboot.fullname" . }}
  labels:
    app: {{ template "Springboot.name" . }}
    chart: {{ template "Springboot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}      
  selector:
    app: {{ template "Springboot.name" . }}
    release: {{ .Release.Name }}