name: Docker Build 🚀

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  app: sample-springboot
  repository: ${{ secrets.DOCKER_REPO }}/docker
  image_name: ${{ env.repository }}/${{ env.app }}
  image_tag: ${{ github.sha }}
jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Timezone to Asia/Seoul
        run: |
          sudo ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "Asia/Seoul" | sudo tee /etc/timezone
        shell: bash          

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: SPRING_PROFILES_ACTIVE=dev ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test

  build:
    needs: gradle           # step_name
    name: Docker Build
    runs-on: ubuntu-22.04
    steps:
      - name: Building Docker Image
        run: |
          ls -al
          docker login ${{ secrets.DOCKER_REPO }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ env.image_name }}:${ emv.image_tag }} -t ${{ env.image_name }}:latest .

          docker push ${{ env.image_name }}:${ emv.image_tag }}
          docker push ${{ env.image_name }}:latest

  deployment:
    name: Argo Deployment
    runs-on: ubuntu-22.04
    steps:      
      - uses: actions/checkout@v4
        with:
          ref: "chart"
          submodules: 'recursive'

      - name: change values.yaml
        run: |
          sed -i "s/tag: \"\"/tag: \"${{ env.dockerimage_tag }}\"/g" values.yaml

      - name: git push
        run: |
          git config --global user.email "GitHub Actions Bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add values.yaml
          git commit -m "change image tag: ${{ env.dockerimage_tag }}"
          git pull origin charts
          git push origin charts